language: c
env:
  global:
    - IDE_VERSION=1.8.5
  matrix:
  - BOARD=esp8266:esp8266:nodemcuv2:CpuFrequency=80,FlashSize=4M3M
  - BOARD=espressif:esp32:esp32:PartitionScheme=min_spiffs,FlashMode=dio,FlashFreq=80,FlashSize=4M,DebugLevel=none
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - rm arduino-$IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$IDE_VERSION /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - mkdir $HOME/Arduino
  - ln -s $PWD/software/firmware/source/libraries $HOME/Arduino/libraries
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs ;
      arduino --install-boards esp8266:esp8266 ;
      arduino --board $BOARD --save-prefs ;
      arduino --pref "compiler.warning_level=all" --save-prefs ;
      arduino --pref "custom_LwIPVariant=nodemcuv2_Prebuilt" --save-prefs ;
    fi
  - if [[ "$BOARD" =~ "espressif:esp32:" ]]; then
      arduino --pref "boardsmanager.additional.urls=https://dl.espressif.com/dl/package_esp32_index.json" --save-prefs ;
      arduino --install-boards espressif:esp32 ;
      arduino --board $BOARD --save-prefs ;
      arduino --pref "compiler.warning_level=all" --save-prefs ;
      cd $HOME/.arduino15/packages/esp32/hardware/esp32/1.0.0//tools/sdk/lib ;
      rm -f libbt.a ;
      cp $TRAVIS_BUILD_DIR/software/firmware/binaries/ESP32/misc/libbt.a . ;
      rm -f libesp32.a ;
      cp $TRAVIS_BUILD_DIR/software/firmware/binaries/ESP32/misc/libesp32.a.80MHz libesp32.a ;
      cd $HOME/.arduino15/packages/esp32/hardware/esp32/1.0.0/ ;
      sed -i 's/esp32.upload.maximum_size=1310720/esp32.upload.maximum_size=1966080/g' boards.txt ;
      sed -i 's/esp32.build.f_cpu=240000000L/esp32.build.f_cpu=80000000L/g' boards.txt ;
      cd $TRAVIS_BUILD_DIR ;
    fi
  
script:
  - arduino --verify --verbose-build --board $BOARD $PWD/software/firmware/source/SoftRF/SoftRF.ino

notifications:
  email:
    on_success: change
    on_failure: change

