name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'cpx_ada'
          - 'feather_m0_express'
          - 'metro_m0'
          - 'feather_m4_express'
          - 'metro_m4'
          - 'grand_central'
          - 'neotrellis_m4'
          - 'pyportal'
          - 'pyportal_titano'
          - 'matrixportal'
          - 'pybadge'
          - 'metroesp32s2'
          - 'nrf52840'
          - 'cpb'
          - 'clue'
          - 'feather_rp2040'
          - 'uno'

    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

    - name: clang
      # skip clang for fatfs (ff) to make it easier to compare and upgrade
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -e "./examples/SdFat_format/*" -r .

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit SPIFlash Library"
      run: bash ci/doxy_gen_and_deploy.sh

    - name: Move build artifacts into place
      run: |
            mkdir build
            find -name "*.uf2" -ls
            for i in examples/*/build/*/*.uf2; do if [ -f $i ]; then j=${i##*/}; j=${j%%*.}; mv $i build/$j-${{ matrix.arduino-platform }}.uf2; fi done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
            build/*.hex
            build/*.bin
            build/*.uf2

    - name: Zip release files
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        if [ -d build ]; then
            (
            echo "Built from Adafruit SPIFlash Library `git describe --tags` for ${{ matrix.arduino-platform }}"
            echo "Source code: https://github.com/adafruit/Adafruit_SPIFlash"
            echo "Adafruit Learning System: https://learn.adafruit.com/"
            ) > build/README.txt
            cd build && zip -9 -o ${{ matrix.arduino-platform }}.zip *.hex *.bin *.uf2 *.txt
        fi

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/${{ matrix.arduino-platform }}.zip
        fail_on_unmatched_files: false
        body: "Select the zip file corresponding to your board from the list below."