name: STM32LowPower Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  astyle_check:
    runs-on: ubuntu-latest
    name: AStyle check
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@main

    - name: Astyle check
      id: Astyle
      uses: stm32duino/actions/astyle-check@main

    # Use the output from the `Astyle` step
    - name: Astyle Errors
      if: failure()
      run: |
        cat ${{ steps.Astyle.outputs.astyle-result }}
        exit 1
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check
    steps:
    - uses: actions/checkout@main
    - uses: arduino/actions/libraries/spell-check@master
      with:
        ignore-words-list: "./extras/codespell-ignore-words-list.txt"
  lib_build:
    runs-on: ubuntu-latest
    name: Library compilation
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@main

    - name: Compilation
      id: Compile
      uses: stm32duino/actions/compile-examples@main
      with:
        board-pattern: ".*NUCLEO.*"
        libraries: "STM32duino RTC"

    # Use the output from the `Compile` step
    - name: Compilation Errors
      if: failure()
      run: |
        cat ${{ steps.Compile.outputs.compile-result }}
        exit 1
